routes/web.php
<?php

use App\Http\Controllers\Cameras\CameraController;
use App\Http\Controllers\Users\LoginController;
use App\Http\Controllers\Users\UserCameraController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//---------------------------------------   admin group start   ---------------------------------------

Route::get('/login',[\App\Http\Controllers\Auth\LoginController::class,'login'])->name('login');
Route::post('/login',[\App\Http\Controllers\Auth\LoginController::class,'auth'])->name('auth.login');
Route::post('/logout',[\App\Http\Controllers\Auth\LoginController::class,'logout'])->name('logout');

Route::group(['prefix' => 'dashboard','middleware' => 'auth:sanctum'], function (){
    Route::get('/index', function (){
        return view('dashboard.index');
    })->name('dashboard');
    Route::get('cameras/index',[CameraController::class,'index'])->name('cameras.index');
    Route::get('cameras/create',[CameraController::class,'create'])->name('cameras.create');
    Route::post('cameras/store',[CameraController::class,'store'])->name('cameras.store');
    Route::get('cameras/{camera}/edit',[CameraController::class,'edit'])->name('cameras.edit');
    Route::get('cameras/{camera}/show',[CameraController::class,'show'])->name('cameras.show');
    Route::get('camera/localip',[CameraController::class,'getLocalIp'])->name('camera.localip');
    Route::get('camera/{camera_id}/localip',[CameraController::class,'checkping'])->name('camera.localip.check');
    Route::get('camera/checkall',[CameraController::class,'checkAllPing'])->name('camera.localip.checkAll');
    Route::put('cameras/{camera}',[CameraController::class,'update'])->name('cameras.update');
    Route::delete('cameras/{camera}',[CameraController::class,'destroy'])->name('cameras.delete');
});
Route::post('/ajax/rahbarId',[CameraController::class, 'ajaxGetRahbarId'])->name('ajax.getRahbarId');
Route::post('/ajax/getId',[CameraController::class, 'ajaxGetSubId'])->name('ajax.getSubId');
Route::post('/ajax/getBinolar',[CameraController::class, 'ajaxXonalar'])->name('ajax.xonalar');
//---------------------------------------   admin group end   ---------------------------------------


//---------------------------------------   users group start   ---------------------------------------

Route::group(['prefix' => 'users','as' => 'users.' ], function (){
    Route::get('/',[LoginController::class, 'showLogin'])->name('loginPage');
    Route::post('/user/login',[LoginController::class, 'login'])->name('login');
    Route::post('/user/logout',[LoginController::class, 'logout'])->name('logout');

    Route::get('/index',[UserCameraController::class,'index'])->name('index');
    Route::get('{uuid}/show',[UserCameraController::class,'show'])->name('camera.show');
});
//---------------------------------------   users group end   ---------------------------------------

Route::get('/',[CameraController::class,'favourite']);
Route::get('/show/{uuid}',[CameraController::class,'showFavouriteCamera'])->name('web.camera');

Route::get('/show/camera/{bino}',[CameraController::class,'showCamera'])->name('web.cameras');
Route::get('/show/{bino}/{xona}',[CameraController::class,'showFavouriteCameras'])->name('web.camera.fav');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * App\Models\User
 *
 * @property int $id
 * @property string $name
 * @property string $login
 * @property mixed $password
 * @property int $role
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
 * @property-read int|null $tokens_count
 * @method static \Database\Factories\UserFactory factory($count = null, $state = [])
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLogin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRole($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Users/LoginController.php
<?php

namespace App\Http\Controllers\Users;

use App\Domain\Cameras\Models\Camera;
use App\Http\Controllers\Controller;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class LoginController extends Controller
{
    public function showLogin()
    {
        return view('dashboard.auth.login');
    }

    public function login(Request $request)
    {
        $client = new Client();
        $response = $client->request('POST', 'https://uniwork.buxdu.uz/api/login.asp', [
            'form_params' => [
                'login' => $request->login,
                'parol' => $request->parol,
                'avtorizatsiya' => 1,
            ]
        ]);
        $result_error = json_decode($response->getBody());

        if (isset($result_error->code) == false) {
            $result = json_decode($response->getBody())->id;
            $result_fio = json_decode($response->getBody())->fio;
            $result_department = json_decode($response->getBody())->department;
            Session::put('id', $result);
            Session::put('fio', $result_fio);
            Session::put('department', $result_department);

            $user = Camera::query()
                ->orWhere('rahbarlar->id->rahbar', Session::get('id'))
                ->orWhere('rahbarlar->id->rector', Session::get('id'))
                ->orWhere('rahbarlar->id->rahbar_sub', Session::get('id'))
                ->first();
            if ($user) {
                return redirect()->route('users.index');
            } else {
                return redirect()->back();
            }

        } else {
            $err = $result_error->error->message;
            return redirect()->back()->with("xato", $err);
        }
    }

    public function logout(Request $request)
    {
        $request->flush();
        Session::flush();

        return redirect()->route('users.loginPage');
    }
}

app/Http/Controllers/Users/UserCameraController.php
<?php

namespace App\Http\Controllers\Users;

use App\Domain\Cameras\Models\Camera;
use App\Domain\Cameras\Repositories\CameraRepository;
use App\Filters\AdminCameraFilter;
use App\Filters\UserCameraFilter;
use App\Http\Controllers\Controller;
use App\Http\Requests\AdminFilterRequest;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class UserCameraController extends Controller
{
    /**
     * @var mixed
     */
    public mixed $cameras;

    public mixed $binolar;

    public mixed $departments;

    /**
     * @param CameraRepository $cameraRepository
     * @throws GuzzleException
     */
    public function __construct(CameraRepository $cameraRepository)
    {
        $client = new Client();
        $this->cameras = $cameraRepository;
        $this->binolar = json_decode($client->request('POST','https://uniwork.buxdu.uz/api/binolar.asp')->getBody())->binolar;
        $this->departments = json_decode($client->request('POST','https://uniwork.buxdu.uz/api/departments.asp')->getBody())->departments;
    }

    /**
     * @param AdminFilterRequest $request
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws BindingResolutionException
     */
    public function index(AdminFilterRequest $request)
    {
        $filter = app()->make(UserCameraFilter::class, ['queryParams' => array_filter($request->validated())]);
        return view('users.layouts.index',[
            'cameras' => $this->cameras->getBySectionCamera($filter),
            'binolar' => $this->binolar
        ]);
    }

    /**
     * @param $uuid
     * @return Application|Factory|View|\Illuminate\Foundation\Application|RedirectResponse
     */
    public function show($uuid)
    {
        $camera = Camera::where('uuid','=',$uuid)->first();
        if (isset($camera) && ($camera->orWhere('rahbarlar->id->rahbar', Session::get('id')) || $camera->orWhere('rahbarlar->id->rahbar_sub', Session::get('id')) || $camera->orWhere('rahbarlar->id->rector', Session::get('id')))) {
            return view('users.cameras.show',[
                'camera' => $camera
            ]);
        } else {
            return redirect()->back();
        }
    }
}

resources/views/users/partials/footer.blade.php
<div class="navbar navbar-sm navbar-footer border-top">
    <div class="container-fluid justify-content-center">
        <span>&copy; 1930 - {{ date('Y') }} <a target="_blank" href="https://buxdu.uz">BuxDU</a></span>
    </div>
</div>

resources/views/users/partials/mainbar.blade.php
<div class="navbar navbar-dark navbar-expand-lg navbar-static border-bottom border-bottom-white border-opacity-10">
    <div class="container-fluid">
        <div class="d-flex d-lg-none me-2">
            <button type="button" class="navbar-toggler sidebar-mobile-main-toggle rounded-pill">
                <i class="ph-list"></i>
            </button>
        </div>

        <div class="navbar-brand flex-1 flex-lg-0">
            <a href="#" style="margin-left: -20px;" class="d-inline-flex align-items-center">
                <img src="{{ asset('logo_uz.svg') }}" alt="buxdu logo" style="width: 170px; height: 50px;">
            </a>
        </div>



        <ul class="nav flex-row justify-content-end order-1 order-lg-2">

            <li class="nav-item nav-item-dropdown-lg dropdown ms-lg-2">
                <a href="#" class="navbar-nav-link align-items-center rounded-pill p-1" data-bs-toggle="dropdown">
                    <div class="status-indicator-container">
                        <img src="{{ asset('user.jpg') }}" class="w-32px h-32px rounded-pill" alt="">
                        <span class="status-indicator bg-success"></span>
                    </div>
                    <span class="d-none d-lg-inline-block mx-lg-2">{{ \Illuminate\Support\Facades\Session::get('fio') }}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-end">
                    <a href="#" class="dropdown-item">
                        <i class="ph-user-circle me-2"></i>
                        My profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('users.logout') }}"
                       onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="ph-sign-out me-2"></i>
                        {{ __('Chiqish') }}
                    </a>

                    <form id="logout-form" action="{{ route('users.logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/users/partials/navbar.blade.php
<div class="page-header page-header-light shadow">
    <div class="page-header-content d-lg-flex">
        <div class="d-flex">
            <h4 class="page-title mb-0">
                Admin - <span class="fw-normal">Dashboard</span>
            </h4>

            <a href="#page_header" class="btn btn-light align-self-center collapsed d-lg-none border-transparent rounded-pill p-0 ms-auto" data-bs-toggle="collapse">
                <i class="ph-caret-down collapsible-indicator ph-sm m-1"></i>
            </a>
        </div>
    </div>

{{--    <div class="page-header-content d-lg-flex border-top">--}}
{{--        <div class="d-flex">--}}
{{--            <div class="breadcrumb py-2">--}}
{{--                <a href="index.html" class="breadcrumb-item"><i class="ph-house"></i></a>--}}
{{--                <a href="#" class="breadcrumb-item">Home</a>--}}
{{--                <span class="breadcrumb-item active">Dashboard</span>--}}
{{--            </div>--}}

{{--            <a href="#breadcrumb_elements" class="btn btn-light align-self-center collapsed d-lg-none border-transparent rounded-pill p-0 ms-auto" data-bs-toggle="collapse">--}}
{{--                <i class="ph-caret-down collapsible-indicator ph-sm m-1"></i>--}}
{{--            </a>--}}
{{--        </div>--}}
{{--    </div>--}}
</div>

resources/views/users/partials/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-lg">

    <!-- Sidebar content -->
    <div class="sidebar-content">

        <!-- Sidebar header -->
        <div class="sidebar-section">
            <div class="sidebar-section-body d-flex justify-content-center">
                <h5 class="sidebar-resize-hide flex-grow-1 my-auto">Menu</h5>

                <div>
                    <button type="button"
                            class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
                        <i class="ph-arrows-left-right"></i>
                    </button>

                    <button type="button"
                            class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-mobile-main-toggle d-lg-none">
                        <i class="ph-x"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- /sidebar header -->


        <!-- Main navigation -->
        <div class="sidebar-section">
            <ul class="nav nav-sidebar" data-nav-type="accordion">
                <!-- Main -->
                <li class="nav-item-header pt-0">
                    <div class="text-uppercase fs-sm lh-sm opacity-50 sidebar-resize-hide">Main</div>
                    <i class="ph-dots-three sidebar-resize-show"></i>
                </li>
                <li class="nav-item">
                    <a href="{{ route('users.index') }}" class="nav-link active">
                        <i class="ph-house"></i>
                        <span>Cameralarim</span>
                    </a>
                </li>
{{--                <li class="nav-item nav-item-submenu">--}}
{{--                    <a href="#" class="nav-link">--}}
{{--                        <i class="ph-layout"></i>--}}
{{--                        <span>Layouts</span>--}}
{{--                    </a>--}}
{{--                    <ul class="nav-group-sub collapse">--}}
{{--                        <li class="nav-item"><a href="#" class="nav-link active">Cameralar</a></li>--}}
{{--                        <li class="nav-item"><a href="#" class="nav-link">Layout 2</a></li>--}}
{{--                        <li class="nav-item"><a href="#" class="nav-link">Layout 3</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>