routes/web.php
<?php

use App\Http\Controllers\Cameras\CameraController;
use App\Http\Controllers\Users\LoginController;
use App\Http\Controllers\Users\UserCameraController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//---------------------------------------   admin group start   ---------------------------------------

Route::get('/login',[\App\Http\Controllers\Auth\LoginController::class,'login'])->name('login');
Route::post('/login',[\App\Http\Controllers\Auth\LoginController::class,'auth'])->name('auth.login');
Route::post('/logout',[\App\Http\Controllers\Auth\LoginController::class,'logout'])->name('logout');

Route::group(['prefix' => 'dashboard','middleware' => 'auth:sanctum'], function (){
    Route::get('/index', function (){
        return view('dashboard.index');
    })->name('dashboard');
    Route::get('cameras/index',[CameraController::class,'index'])->name('cameras.index');
    Route::get('cameras/create',[CameraController::class,'create'])->name('cameras.create');
    Route::post('cameras/store',[CameraController::class,'store'])->name('cameras.store');
    Route::get('cameras/{camera}/edit',[CameraController::class,'edit'])->name('cameras.edit');
    Route::get('cameras/{camera}/show',[CameraController::class,'show'])->name('cameras.show');
    Route::get('camera/localip',[CameraController::class,'getLocalIp'])->name('camera.localip');
    Route::get('camera/{camera_id}/localip',[CameraController::class,'checkping'])->name('camera.localip.check');
    Route::get('camera/checkall',[CameraController::class,'checkAllPing'])->name('camera.localip.checkAll');
    Route::put('cameras/{camera}',[CameraController::class,'update'])->name('cameras.update');
    Route::delete('cameras/{camera}',[CameraController::class,'destroy'])->name('cameras.delete');
});
Route::post('/ajax/rahbarId',[CameraController::class, 'ajaxGetRahbarId'])->name('ajax.getRahbarId');
Route::post('/ajax/getId',[CameraController::class, 'ajaxGetSubId'])->name('ajax.getSubId');
Route::post('/ajax/getBinolar',[CameraController::class, 'ajaxXonalar'])->name('ajax.xonalar');
//---------------------------------------   admin group end   ---------------------------------------


//---------------------------------------   users group start   ---------------------------------------

Route::group(['prefix' => 'users','as' => 'users.' ], function (){
    Route::get('/',[LoginController::class, 'showLogin'])->name('loginPage');
    Route::post('/user/login',[LoginController::class, 'login'])->name('login');
    Route::post('/user/logout',[LoginController::class, 'logout'])->name('logout');

    Route::get('/index',[UserCameraController::class,'index'])->name('index');
    Route::get('{uuid}/show',[UserCameraController::class,'show'])->name('camera.show');
});
//---------------------------------------   users group end   ---------------------------------------

Route::get('/',[CameraController::class,'favourite']);
Route::get('/show/{uuid}',[CameraController::class,'showFavouriteCamera'])->name('web.camera');

Route::get('/show/camera/{bino}',[CameraController::class,'showCamera'])->name('web.cameras');
Route::get('/show/{bino}/{xona}',[CameraController::class,'showFavouriteCameras'])->name('web.camera.fav');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * App\Models\User
 *
 * @property int $id
 * @property string $name
 * @property string $login
 * @property mixed $password
 * @property int $role
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
 * @property-read int|null $tokens_count
 * @method static \Database\Factories\UserFactory factory($count = null, $state = [])
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLogin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRole($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Users/LoginController.php
<?php

namespace App\Http\Controllers\Users;

use App\Domain\Cameras\Models\Camera;
use App\Http\Controllers\Controller;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class LoginController extends Controller
{
    public function showLogin()
    {
        return view('dashboard.auth.login');
    }

    public function login(Request $request)
    {
        $client = new Client();
        $response = $client->request('POST', 'https://uniwork.buxdu.uz/api/login.asp', [
            'form_params' => [
                'login' => $request->login,
                'parol' => $request->parol,
                'avtorizatsiya' => 1,
            ]
        ]);
        $result_error = json_decode($response->getBody());

        if (isset($result_error->code) == false) {
            $result = json_decode($response->getBody())->id;
            $result_fio = json_decode($response->getBody())->fio;
            $result_department = json_decode($response->getBody())->department;
            Session::put('id', $result);
            Session::put('fio', $result_fio);
            Session::put('department', $result_department);

            $user = Camera::query()
                ->orWhere('rahbarlar->id->rahbar', Session::get('id'))
                ->orWhere('rahbarlar->id->rector', Session::get('id'))
                ->orWhere('rahbarlar->id->rahbar_sub', Session::get('id'))
                ->first();
            if ($user) {
                return redirect()->route('users.index');
            } else {
                return redirect()->back();
            }

        } else {
            $err = $result_error->error->message;
            return redirect()->back()->with("xato", $err);
        }
    }

    public function logout(Request $request)
    {
        $request->flush();
        Session::flush();

        return redirect()->route('users.loginPage');
    }
}

app/Http/Controllers/Users/UserCameraController.php
<?php

namespace App\Http\Controllers\Users;

use App\Domain\Cameras\Models\Camera;
use App\Domain\Cameras\Repositories\CameraRepository;
use App\Filters\AdminCameraFilter;
use App\Filters\UserCameraFilter;
use App\Http\Controllers\Controller;
use App\Http\Requests\AdminFilterRequest;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class UserCameraController extends Controller
{
    /**
     * @var mixed
     */
    public mixed $cameras;

    public mixed $binolar;

    public mixed $departments;

    /**
     * @param CameraRepository $cameraRepository
     * @throws GuzzleException
     */
    public function __construct(CameraRepository $cameraRepository)
    {
        $client = new Client();
        $this->cameras = $cameraRepository;
        $this->binolar = json_decode($client->request('POST','https://uniwork.buxdu.uz/api/binolar.asp')->getBody())->binolar;
        $this->departments = json_decode($client->request('POST','https://uniwork.buxdu.uz/api/departments.asp')->getBody())->departments;
    }

    /**
     * @param AdminFilterRequest $request
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     * @throws BindingResolutionException
     */
    public function index(AdminFilterRequest $request)
    {
        $filter = app()->make(UserCameraFilter::class, ['queryParams' => array_filter($request->validated())]);
        return view('users.layouts.index',[
            'cameras' => $this->cameras->getBySectionCamera($filter),
            'binolar' => $this->binolar
        ]);
    }

    /**
     * @param $uuid
     * @return Application|Factory|View|\Illuminate\Foundation\Application|RedirectResponse
     */
    public function show($uuid)
    {
        $camera = Camera::where('uuid','=',$uuid)->first();
        if (isset($camera) && ($camera->orWhere('rahbarlar->id->rahbar', Session::get('id')) || $camera->orWhere('rahbarlar->id->rahbar_sub', Session::get('id')) || $camera->orWhere('rahbarlar->id->rector', Session::get('id')))) {
            return view('users.cameras.show',[
                'camera' => $camera
            ]);
        } else {
            return redirect()->back();
        }
    }
}

resources/views/users/layouts/index.blade.php
@extends('users.layouts.master')
@section('content')
    <div id="filter-card" class="card shadow-lg">
        <form action="{{ route('users.index') }}" method="get">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <label for="bino">Bino</label>
                        <select name="bino" id="bino" class="form-control">
                            <option value="">Binoni tanlang!</option>
                            @foreach($binolar as $bino)
                                @if(request()->bino == $bino->id)
                                    <option selected value="{{$bino->id}}">{{ $bino->name }}</option>
                                @else
                                    <option value="{{$bino->id}}">{{ $bino->name }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="qavat">Qavat</label>
                        <select name="qavat" id="qavat" class="form-control">
                            <option value="">Qavatni tanlang!</option>
                            @if(request()->qavat == 1)
                                <option selected value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            @elseif(request()->qavat == 2)
                                <option value="1">1</option>
                                <option selected value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            @elseif(request()->qavat == 3)
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option selected value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            @elseif(request()->qavat == 4)
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option selected value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            @elseif(request()->qavat == 5)
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option selected value="5">5</option>
                                <option value="6">6</option>
                            @elseif(request()->qavat == 6)
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option selected value="6">6</option>
                            @else
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            @endif
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="xona">Xonalar</label>
                        <select name="xona" id="xona" class="form-control">

                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="title">Nomi</label>
                        <input type="search" class="form-control" name="title" id="title" value="{{ request()->title }}" placeholder="camera nomi...">
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-secondary w-100">Qidirish</button>
            </div>
        </form>
    </div>
    <div class="card">
        <div class="card-header d-flex flex-column">
            <div class="d-flex align-items-center justify-content-between">
                <h1>Cameralar ro'yxati</h1>
                <button id="ft-btn" type="button" class="btn btn-info"><i class="ph-sort-descending me-2"></i>Filter</button>
            </div>
        </div>
        <div class="card-body row">
            @foreach($cameras as $camera)
                <div class="col-md-3">
                    <div class="card">
                        <div class="card-header text-center">
                            <h3>
                                <a>{{ $camera->title }}</a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-2">
                            <h2>Bino: {{ $camera->bino }}</h2>
                            <h2>Qavat: {{ $camera->qavat }}</h2>
                            <h2>Xona: {{ $camera->xonalar }}</h2>
                        </div>
                        <div class="card-footer text-end">
                            <a href="{{ route('users.camera.show',$camera->uuid) }}" class="btn btn-sm btn-primary">Ko'rish</a>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            @endforeach
        </div>
        <div class="card-footer">
            {{ $cameras->appends(request()->all())->links() }}
        </div>
    </div>
@endsection
@push('user_script')
    <script>
        $(document).ready(function () {
            var qavat = '{{ request()->qavat }}';
            var bino = '{{ request()->bino }}';

            @if(count(request()->all()) == 0)
            $('#filter-card').hide();
            @else
            $('#filter-card').show();
            @endif
            $("#ft-btn").click(function () {
                $('#filter-card').slideToggle(1000);
            });


            $.ajaxSetup({
                headers:
                    { 'X-CSRF-TOKEN': '{{ csrf_token() }}' }
            });

            $("#qavat").change(function (){
                qavat = $(this).val();
                $("#xona").html('');
                $.ajax({
                    url: '{{ route('ajax.xonalar') }}',
                    method: 'POST',
                    data: {
                        bino: bino,
                        qavat: qavat
                    },
                    success: function (response) {
                        console.log(response);
                        $("#xona").append(`
                            <option value="">Xonani tanlang!</option>
                        `);
                        $.each(response.binolar, function (index, xona) {
                            $("#xona").append(`
                                <option value="${xona.xona_nomi}">${xona.xona_nomi}</option>
                            `);
                        });
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            });

            $("#bino").change(function (){
                bino = $(this).val();
                $("#xona").html('');
                $.ajax({
                    url: '{{ route('ajax.xonalar') }}',
                    method: 'POST',
                    data: {
                        bino: bino,
                        qavat: qavat
                    },
                    success: function (response) {
                        console.log(response);
                        $("#xona").append(`
                            <option value="">Xonani tanlang!</option>
                        `);
                        $.each(response.binolar, function (index, xona) {
                            $("#xona").append(`
                                <option value="${xona.xona_nomi}">${xona.xona_nomi}</option>
                            `);
                        });
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            });
        });
    </script>
@endpush

resources/views/users/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Camera BuxDU</title>

    <!-- Global stylesheets -->
    <link href="{{ asset('assets/fonts/inter/inter.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/icons/phosphor/styles.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/css/ltr/all.min.css') }}" id="stylesheet" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
@stack('user_style')
<!-- Core JS files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{{ asset('assets/demo/demo_configurator.js')}}"></script>
    <script src="{{ asset('assets/js/bootstrap/bootstrap.bundle.min.js')}}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script src="{{ asset('assets/js/vendor/visualization/d3/d3.min.js')}}"></script>
    <script src="{{ asset('assets/js/vendor/visualization/d3/d3_tooltip.js')}}"></script>

    <script src="{{ asset('assets/js/app.js') }}"></script>
    <script src="{{ asset('assets/demo/pages/dashboard.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/streamgraph.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/sparklines.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/lines.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/areas.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/donuts.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/bars.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/progress.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/heatmaps.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/pies.js')}}"></script>
    <script src="{{ asset('assets/demo/charts/pages/dashboard/bullets.js')}}"></script>
    <!-- /theme JS files -->
    @stack('user_script')
</head>

<body>

<!-- Main navbar -->
@include('users.partials.mainbar')
<!-- /main navbar -->


<!-- Page content -->
<div class="page-content">

    <!-- Main sidebar -->
@include('users.partials.sidebar')
<!-- /main sidebar -->


    <!-- Main content -->
    <div class="content-wrapper">

        <!-- Inner content -->
        <div class="content-inner">

            <!-- Page header -->
        @include('users.partials.navbar')
        <!-- /page header -->


            <!-- Content area -->
            <div class="content">

                @yield('content')

            </div>
            <!-- /content area -->


            <!-- Footer -->
        @include('users.partials.footer')
        <!-- /footer -->

        </div>
        <!-- /inner content -->

    </div>
    <!-- /main content -->

</div>
<!-- /page content -->

</body>
</html>